"""LAMMPS data-file conversion helpers."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional, Union

import numpy as np

DEFAULT_ATOM_MASSES: dict[str, tuple[int, float]] = {
    "H": (1, 1.008),
    "O": (2, 15.999),
    "N": (3, 14.007),
    "Na": (4, 22.990),
    "Cl": (5, 35.450),
    "Ti": (6, 47.867),
}

LATTICE_RE = re.compile(r'lattice="([^"]+)"', re.IGNORECASE)


def read_extxyz_atoms(path: Union[str, Path]) -> tuple[list[tuple[str, float, float, float]], np.ndarray]:
    """Read atoms and lattice from an extended XYZ file."""
    xyz_path = Path(path)
    lines = xyz_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    if len(lines) < 2:
        raise ValueError(f"Extended XYZ file is too short: {xyz_path}")

    atom_count = int(lines[0].split()[0])
    lattice_match = LATTICE_RE.search(lines[1])
    if lattice_match is None:
        raise ValueError(f"No lattice field found in extended XYZ comment line: {xyz_path}")
    lattice_values = [float(value) for value in lattice_match.group(1).split()]
    if len(lattice_values) != 9:
        raise ValueError(f"Expected 9 lattice values, found {len(lattice_values)} in {xyz_path}")
    lattice = np.array(lattice_values, dtype=float).reshape(3, 3)

    atoms: list[tuple[str, float, float, float]] = []
    for line in lines[2 : 2 + atom_count]:
        parts = line.split()
        if len(parts) < 4:
            raise ValueError(f"Invalid atom line in {xyz_path}: {line!r}")
        atoms.append((parts[0], float(parts[-3]), float(parts[-2]), float(parts[-1])))
    if len(atoms) != atom_count:
        raise ValueError(f"Extended XYZ file ended before {atom_count} atoms were read: {xyz_path}")
    return atoms, lattice


def orthorhombic_bounds_from_lattice(lattice: np.ndarray, *, tolerance: float = 1e-8) -> tuple[float, ...]:
    """Return LAMMPS orthorhombic bounds from a diagonal lattice matrix."""
    array = np.asarray(lattice, dtype=float)
    off_diagonal = array.copy()
    np.fill_diagonal(off_diagonal, 0.0)
    if np.max(np.abs(off_diagonal)) > tolerance:
        raise ValueError("Only orthorhombic extended XYZ lattices are supported for now")
    return (0.0, array[0, 0], 0.0, array[1, 1], 0.0, array[2, 2])


def write_lammps_atomic_data(
    atoms: list[tuple[str, float, float, float]],
    bounds: tuple[float, float, float, float, float, float],
    output_path: Union[str, Path],
    *,
    atom_masses: Optional[dict[str, tuple[int, float]]] = None,
    title: str = "LAMMPS data file generated by molsimflow",
) -> Path:
    """Write a LAMMPS `atom_style atomic` data file."""
    masses = atom_masses or DEFAULT_ATOM_MASSES
    unknown = sorted({symbol for symbol, *_ in atoms if symbol not in masses})
    if unknown:
        raise ValueError(f"No atom type/mass configured for elements: {', '.join(unknown)}")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as handle:
        handle.write(f"{title}\n\n")
        handle.write(f"{len(atoms):10d} atoms\n\n")
        handle.write(f"{len(masses):10d} atom types\n\n")
        handle.write(f"{bounds[0]:12.8f} {bounds[1]:12.8f} xlo xhi\n")
        handle.write(f"{bounds[2]:12.8f} {bounds[3]:12.8f} ylo yhi\n")
        handle.write(f"{bounds[4]:12.8f} {bounds[5]:12.8f} zlo zhi\n\n")

        handle.write("Masses\n\n")
        for element, (atom_type, mass) in sorted(masses.items(), key=lambda item: item[1][0]):
            handle.write(f"{atom_type:10d}{mass:10.4f}  # {element:>4s}\n")

        handle.write("\nAtoms  # atomic\n\n")
        for atom_id, (element, x, y, z) in enumerate(atoms, start=1):
            atom_type = masses[element][0]
            handle.write(
                f" {atom_id:6d} {atom_type:3d} {x:15.9f} {y:15.9f} {z:15.9f} # {element:>2s}\n"
            )
    return output


def convert_extxyz_to_lammps_atomic_data(
    xyz_path: Union[str, Path],
    output_path: Union[str, Path],
    *,
    atom_masses: Optional[dict[str, tuple[int, float]]] = None,
) -> Path:
    """Convert an orthorhombic extended XYZ file to LAMMPS atomic data."""
    atoms, lattice = read_extxyz_atoms(xyz_path)
    bounds = orthorhombic_bounds_from_lattice(lattice)
    return write_lammps_atomic_data(atoms, bounds, output_path, atom_masses=atom_masses)
